
export const CREATE_MAIN_OPINION = "CREATE_MAIN_OPINION";
export const ADD_SUBSEQUENT_OPINION = "ADD_SUBSEQUENT_OPINION";
export const UPDATE_MAIN_OPINION = "UPDATE_MAIN_OPINION";
export const UPDATE_SUBSEQUENT_OPINION = "UPDATE_SUBSEQUENT_OPINION";

export const CATEGORY_MAIN = "main"
export const CATEGORY_SUBSEQUENT = "subsequent"